[workspace]
members = [
    "src/backend/user",
    "src/backend/course",
    "src/backend/shared",
    "src/backend/storage",
    "src/backend/paginator",
    "src/backend/towntalk",
    "src/backend/utilities",
    "src/backend/competition",
]
resolver = "2"
