[package]
name = "grindarena"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.18.5"
serde = "1.0.219"
utilities = { path = "../utilities" }